from flask import Flask, render_template, request, Response, redirect, url_for
import sqlite3
import os
from openai import OpenAI
import base64
import io
import re
from nltk.translate.gleu_score import sentence_gleu
import nltk
from sacrebleu.metrics import TER
from datetime import datetime
import pytz
from flask import session

# ---------------------------
# DATABASE PATH
# ---------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "db.db")

try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    pass

from nltk.translate.bleu_score import sentence_bleu

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY", "dev-key")
RECRUITER_USER = os.getenv("ADMIN_USER", "admin")
RECRUITER_PASS = os.getenv("ADMIN_PASS", "novox123")


# ---------------------------
# INIT DB
# ---------------------------
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Create table if not exists
    c.execute("""
    CREATE TABLE IF NOT EXISTS results (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        first_name TEXT,
        last_name TEXT,
        email TEXT,
        test_type TEXT,
        language TEXT,
        answer TEXT,

        translation_score TEXT,
        interpretation_score TEXT,
        status TEXT,

        audio1 TEXT,
        audio2 TEXT,
        audio3 TEXT,
        audio4 TEXT,

        transcription1 TEXT,
        transcription2 TEXT,
        transcription3 TEXT,
        transcription4 TEXT,

        created_at TEXT
    )
    """)

    
    columns = [
        ("editing_score", "TEXT"),
        ("final_score", "REAL"),
        ("post_edit_score", "TEXT"),
        ("gleu_score", "REAL"),
        ("bleu_score", "REAL"),
        ("ter_score", "REAL"),
        ("ai_component", "REAL"),
        ("bleu_component", "REAL"),
        ("ter_component", "REAL"),
        ("t1_en", "TEXT"),
        ("t2_en", "TEXT"),
        ("t3_en", "TEXT"),
        ("t4_en", "TEXT"),
        ("flag", "TEXT"),
    ]

    for col, col_type in columns:
        try:
            c.execute(f"ALTER TABLE results ADD COLUMN {col} {col_type}")
        except:
            pass

    conn.commit()
    conn.close()
init_db()

# ---------------------------
# ORIGINAL AUDIO TEXTS
# ---------------------------
ORIGINAL_AUDIO_TEXTS = [
    "They are holding a public meeting on the new community pool.",
    "Visiting professors can be boring.",
    "The execution of the document was witnessed by the clerk.",
    "The doctor decided to let the patient go."
]

REVERSE_TEXTS = [
    "A public meeting will be held next week to discuss the development of the new community pool, including its proposed location, budget allocation, and expected impact on local residents.",
    "Some professors may struggle to engage students effectively in the classroom, particularly when teaching large groups or relying heavily on traditional lecture-based methods.",
    "The document must be signed in the presence of a notary public, who will verify the identity of all parties involved and ensure that the signing is conducted in accordance with legal requirements.",
    "After evaluating the patient’s progress and reviewing the test results, the doctor decided to discharge the patient with specific instructions for follow-up care and medication."
]

# ---------------------------
# HELPERS
# ---------------------------
def detect_ai(text):
    try:
        prompt = f"""
        Analyze if this translation was likely generated by AI.

        Text:
        {text}

        Respond with:
        Likelihood (0 to 1) and a short explanation.
        """

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}]
        )

        output = response.choices[0].message.content

        if "0.8" in output or "0.9" in output or "1" in output:
            return 0.8
        return 0.3

    except:
        return 0.3

def apply_completion_penalty(original, candidate, score):
    try:
        if not candidate:
            return 0

        ratio = len(candidate.split()) / len(original.split())

        # If less than 50% completed → heavy penalty
        if ratio < 0.5:
            return round(score * 0.5, 2)

        # If less than 80% → moderate penalty
        elif ratio < 0.8:
            return round(score * 0.75, 2)

        return score
    except:
        return score

def calculate_ter(reference, candidate):
    try:
        ter = TER()
        score = ter.sentence_score(candidate, [reference]).score
        return round(score, 2)
    except:
        return 100

def calculate_bleu(reference, candidate):
    try:
        ref_tokens = reference.split()
        cand_tokens = candidate.split()

        score = sentence_bleu([ref_tokens], cand_tokens)
        return round(score, 2)
    except:
        return 0

def combine_scores(ai_score, gleu_score):
    try:
        # ai_score is from 0–10
        # gleu_score is from 0–1 → convert to 0–10
        gleu_scaled = gleu_score * 10 if gleu_score else 0

        final = (ai_score * 0.7) + (gleu_scaled * 0.3)
        return round(final, 2)
    except:
        return ai_score

def get_status(score):
    if score >= 8:
        return "STRONG PASS"
    elif score >= 6:
        return "BORDERLINE"
    else:
        return "FAIL"

def calculate_gleu(reference, candidate):
    try:
        ref_tokens = reference.split()
        cand_tokens = candidate.split()

        score = sentence_gleu([ref_tokens], cand_tokens)
        return round(score, 2)
    except:
        return 0

def extract_all_scores(text):
    try:
        matches = re.findall(r'(\d+)/10', text)
        return [int(m) for m in matches]
    except:
        return []

def decode_audio(base64_audio):
    try:
        header, encoded = base64_audio.split(",", 1)
        return base64.b64decode(encoded)
    except:
        return None

def transcribe_audio(file_obj):
    try:
        file_obj.name = "audio.webm"
        response = client.audio.transcriptions.create(
            file=file_obj,
            model="gpt-4o-transcribe"
        )
        return response.text
    except:
        return ""

def translate_to_english(text):
    try:
        if not text.strip():
            return ""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "Translate the following text to English."},
                {"role": "user", "content": text}
            ]
        )
        return response.choices[0].message.content.strip()
    except:
        return ""

def translate_to_target(text, language):
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        f"You are a professional human translator. "
                        f""Translate as a professional interpreter would, ensuring clarity, fluency, and natural phrasing for real-world communication."
                        f"Avoid literal translation. Use context-appropriate phrasing."
                    )
                },
                {
                    "role": "user",
                    "content": text
                }
            ],
            temperature=0.3
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        print("Translation error:", e)
        return text

def process_audio(base64_audio):
    if not base64_audio:
        return ""
    audio_bytes = decode_audio(base64_audio)
    if not audio_bytes or len(audio_bytes) < 1000:
        return ""
    return transcribe_audio(io.BytesIO(audio_bytes))

# ---------------------------
# SCORING
# ---------------------------
def score_interpretation(original, interpreted, language):
    try:
        if not interpreted.strip():
            return "SCORE: 0/10"

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": f"""
                Evaluate interpretation.

                Source meaning:
                {original}

                Target language: {language}

                Evaluate accuracy, completeness, and fluency.

                Return:
                SCORE: X/10
                Explanation: ...
                """},
                {"role": "user", "content": interpreted}
            ]
        )
        return response.choices[0].message.content.strip()
    except:
        return "SCORE: 0/10"

def score_editing(original, edited):
    try:
        if not edited.strip():
            return "SCORE: 0/10"

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": """Evaluate the edited text.

                1. Check if the FULL text was edited. If parts are missing or only partially edited, clearly state that the response is incomplete.
                2. Evaluate grammar, clarity, and naturalness.
                3. Penalize heavily if the response is incomplete.

                Return:
                FINAL_SCORE: X/10
                Explanation: Brief explanation including whether the response is complete or incomplete.
                """},
                {"role": "user", "content": f"{original}\n{edited}"}
            ]
        )
        return response.choices[0].message.content.strip()
    except:
        return "SCORE: 0/10"

def score_post_edit(mt_text, edited):
    try:
        if not edited.strip():
            return "SCORE: 0/10"

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": """Evaluate the post-edited text.

                1. Check if the FULL text was post-edited. If parts are missing or incomplete, clearly state that the response is incomplete.
                2. Evaluate fluency, accuracy, and corrections.
                3. Penalize incomplete submissions heavily.

                Return:
                FINAL_SCORE: X/10
                Explanation: Explain the quality AND whether the submission is complete or incomplete.
                """},
                {"role": "user", "content": f"{mt_text}\n{edited}"}
            ]
        )
        return response.choices[0].message.content.strip()
    except:
        return "SCORE: 0/10"

# ---------------------------
# ROUTES
# ---------------------------
@app.route("/")
def home():
    success = request.args.get("success")
    language = request.args.get("lang") or request.form.get("language")
    print("LANG RECEIVED:", language)

    if language:
        target_texts = [
            translate_to_target(text, language)
            for text in REVERSE_TEXTS
        ]
    else:
        target_texts = REVERSE_TEXTS

    return render_template(
        "test.html",
        success=success,
        target_texts=target_texts,
        language=language
    )

@app.route("/get_translation")
def get_translation():
    language = request.args.get("lang")

    try:
        if language:
            target_texts = [
                translate_to_target(text, language)
                for text in REVERSE_TEXTS
            ]
        else:
            target_texts = REVERSE_TEXTS

        return {"target_texts": target_texts}

    except Exception as e:
        print("TRANSLATION ERROR:", e)
        return {"target_texts": ORIGINAL_AUDIO_TEXTS}

# ---------------------------
# SUBMIT
# ---------------------------

@app.route("/submit", methods=["GET", "POST"])
def submit():
    if request.method == "GET":
        return redirect(url_for("home"))
    try:
        gleu_score = None
        email = request.form.get("email")
        first_name = request.form.get("first_name")
        last_name = request.form.get("last_name")
        test_type = request.form.get("test_type")
        language = request.form.get("language")

        target_texts = [
            translate_to_target(text, language)
            for text in REVERSE_TEXTS
        ]

        a1 = request.form.get("answer1","")
        a2 = request.form.get("answer2","")
        a3 = request.form.get("answer3","")
        a4 = request.form.get("answer4","")
        edit1 = request.form.get("edit1","")
        mt1 = request.form.get("mt1","")

        
        if test_type == "translation":
            answer = f"{a1}\n\n{a2}\n\n{a3}\n\n{a4}"

        elif test_type == "editing":
            answer = edit1

        elif test_type == "post_editing":
            answer = mt1

        else:
            answer = ""
       
        # ---------------------------
        # SELECT TEXT FOR AI DETECTION
        # ---------------------------
        if test_type == "translation":
            candidate_translation = answer
        elif test_type == "editing":
            candidate_translation = edit1
        elif test_type == "post_editing":
            candidate_translation = mt1
        else:
            candidate_translation = ""  # skip interpretation

        translation_score = "N/A"
        interpretation_score = "N/A"
        editing_score = "N/A"
        post_edit_score = "N/A"
   
        # TRANSLATION

        
        if test_type == "translation":
            r = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role":"system","content":"""Evaluate translation quality.

                    1. Ensure all parts of the text are translated.
                    2. If any section is missing, clearly state that the translation is incomplete.
                    3. Evaluate accuracy, fluency, and terminology.

                    Return:
                    FINAL_SCORE: X/10
                    Explanation: Include both quality and whether the translation is complete or incomplete.
                    """},
                    {"role":"user","content":answer}
                ]
            )
            translation_score = r.choices[0].message.content.strip()

        bleu_improvement = 0
        ter_score = 100
        bleu_score = None
      

        # EDITING

        original_text = ""

        if test_type == "editing" and edit1:
            original_text = """The company dont have enough informations to take a decision about the proyect.
Also, the results that we received from the last quarter is not very clear and
there is many inconsistencies that needs to be reviewed carefully before moving forward.
In addition, the team are not aligned with the new strategy and this create confusion
between departments, which affect negatively the overall performance."""
            reference_text = "The company doesn't have enough information to make a decision about the project."

            # AI score
            editing_score = score_editing(original_text, edit1)

            # BLEU
            bleu_original = calculate_bleu(reference_text, original_text)
            bleu_edited = calculate_bleu(reference_text, edit1)
            bleu_improvement = round(bleu_edited - bleu_original, 2)
            bleu_score = bleu_edited

            # TER
            ter_score = calculate_ter(reference_text, edit1)

        # POST-MT

        mt_original = ""

        if test_type == "post_editing" and mt1:
            mt_original = """The system present many errors and it is not working correct in all devices.
Users is reporting that the application crash frequently when they try to upload files,
and the interface is not intuitive causing confusion. Also, the loading times are too much long
and this make the experience very frustrating for the clients. It is necessary to make improvements
as soon as possible to avoid losing customers."""

            post_edit_score = score_post_edit(mt_original, mt1)

            gleu_score = calculate_gleu(
                "The system presents many errors and does not work correctly on all devices. Users are reporting that the application crashes frequently when they try to upload files, and the interface is not intuitive, causing confusion. Also, the loading times are too long, making the experience very frustrating for clients. Improvements must be made as soon as possible to avoid losing customers.",
                 mt1
            )

            

        # AUDIO
        t1 = process_audio(request.form.get("audio1"))
        t2 = process_audio(request.form.get("audio2"))
        t3 = process_audio(request.form.get("audio3"))
        t4 = process_audio(request.form.get("audio4"))

        rev1 = process_audio(request.form.get("rev_audio1"))
        rev2 = process_audio(request.form.get("rev_audio2"))
        rev3 = process_audio(request.form.get("rev_audio3"))
        rev4 = process_audio(request.form.get("rev_audio4"))

        # TRANSLATE TO ENGLISH
        t1_en = translate_to_english(t1)
        t2_en = translate_to_english(t2)
        t3_en = translate_to_english(t3)
        t4_en = translate_to_english(t4)



        # INTERPRETATION
        if test_type == "interpretation":
            parts = []

            t_en_list = [t1_en, t2_en, t3_en, t4_en]
            rev_list = [rev1, rev2, rev3, rev4]

            for i in range(4):

                # EN → TARGET
                if t_en_list[i]:
                    result1 = score_interpretation(
                        ORIGINAL_AUDIO_TEXTS[i],
                        t_en_list[i],
                        language
                    )
                    parts.append(f"\n📌 AUDIO {i+1} (EN → {language})\n{result1}")

                # TARGET → EN
                if rev_list[i]:
                    reference_text = target_texts[i]  # translated version

                    result2 = score_interpretation(
                        reference_text,
                        rev_list[i],
                        "English"
                    )
                    parts.append(f"\n📌 AUDIO {i+1} ({language} → EN)\n{result2}")

            interpretation_score = "\n".join(parts)

        # SCORES
        def get_score(text):
            scores = extract_all_scores(text)
            return scores[-1] if scores else 0

        ai_component = None
        bleu_component = None
        ter_component = None

        t_score = get_score(translation_score)
        scores = extract_all_scores(interpretation_score)

        if scores:
            i_score = round(sum(scores) / len(scores), 2)
        else:
            i_score = 0
        e_score = get_score(editing_score)
        if test_type == "editing" and original_text:
            e_score = apply_completion_penalty(original_text, edit1, e_score)

        editing_final_score = e_score

        if test_type == "editing":
            ter_scaled = max(0, 10 - (ter_score / 10))
            bleu_bonus = min(10, bleu_improvement * 10) if bleu_improvement > 0 else 0

            ai_component = round(e_score * 0.6, 2)
            bleu_component = round(bleu_bonus * 0.2, 2)
            ter_component = round(ter_scaled * 0.2, 2)
            
            editing_final_score = (
                ai_component +
                bleu_component +
                ter_component
            )

        p_score = get_score(post_edit_score)
        if test_type == "post_editing" and mt_original:
            p_score = apply_completion_penalty(mt_original, mt1, p_score)
        final_score = None


        if test_type == "post_editing":
            final_score = combine_scores(p_score, gleu_score or 0)

        elif test_type == "editing":
            final_score = editing_final_score

        elif test_type == "translation":
            final_score = t_score

        elif test_type == "interpretation":
            final_score = i_score

        final_score = final_score if final_score is not None else 0

        # ---------------------------
        # AI DETECTION
        # ---------------------------
        ai_score = detect_ai(candidate_translation) if candidate_translation else 0

        if ai_score > 0.7:
            if test_type == "translation":
                final_score = min(final_score, 5)  # strong penalty
            else:
                final_score = max(0, final_score - 2)

            flag = "AI suspected"
        else:
            flag = "OK"

        status = get_status(final_score)
        
        eastern = pytz.timezone("America/New_York")
        created_at = datetime.now(eastern).strftime("%Y-%m-%d %H:%M:%S")

        conn = sqlite3.connect(DB_PATH)
        c = conn.cursor()

        c.execute("""
        INSERT INTO results 
        (first_name,last_name,email,test_type,created_at,language,answer,
        translation_score,interpretation_score,editing_score,post_edit_score,
        gleu_score,bleu_score,ter_score,final_score,status,flag,
        ai_component,bleu_component,ter_component,
        transcription1,transcription2,transcription3,transcription4,t1_en, t2_en, t3_en, t4_en)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,(
             first_name,last_name,email,test_type,created_at,language,answer,
             translation_score,interpretation_score,editing_score,post_edit_score,
             gleu_score,bleu_score,ter_score,final_score,status,flag,
             ai_component,bleu_component,ter_component,
             t1,t2,t3,t4,
             t1_en,t2_en,t3_en,t4_en
            ))

        conn.commit()
        conn.close()

        return redirect(url_for("home", success=1))

    except Exception as e:
        return str(e)

# ---------------------------
# AUTH ROUTES
# ---------------------------
@app.route("/login", methods=["GET", "POST"])
def login():
    try:
        if session.get("logged_in"):
            return redirect(url_for("dashboard"))

        if request.method == "POST":
            username = request.form.get("username")
            password = request.form.get("password")

            if username == RECRUITER_USER and password == RECRUITER_PASS:
                session["logged_in"] = True
                return redirect(url_for("dashboard"))
            else:
                return render_template("login.html", error="Invalid credentials")

        return render_template("login.html")
    except Exception as e:
        return str(e)  

# ---------------------------
# DASHBOARD
# ---------------------------

@app.route("/dashboard")
def dashboard():
    try:
        if not session.get("logged_in"):
            return redirect(url_for("login"))

        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        search = request.args.get("search", "")
        status_filter = request.args.get("status", "")

        query = "SELECT * FROM results WHERE 1=1"
        params = []

        if search:
            query += " AND email LIKE ?"
            params.append(f"%{search}%")

        if status_filter:
            query += " AND status = ?"
            params.append(status_filter)

        query += " ORDER BY created_at DESC"

        c.execute(query, params)
        results = c.fetchall()

        conn.close()

        return render_template("dashboard.html", results=results)

    except Exception as e:
        return str(e) 

@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


@app.route("/download")
def download_csv():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    c.execute("SELECT email, language, test_type, status, created_at FROM results")
    rows = c.fetchall()
    conn.close()

    def generate():
        yield "Email,Language,Test Type,Status,Date\n"
        for r in rows:
            yield f"{r[0]},{r[1]},{r[2]},{r[3]},{r[4]}\n"

    return Response(generate(), mimetype="text/csv",
                    headers={"Content-Disposition": "attachment;filename=results.csv"})

@app.route("/result/<int:id>")
def result_detail(id):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    c.execute("SELECT * FROM results WHERE id = ?", (id,))
    result = c.fetchone()
    conn.close()

    return render_template("result.html", r=result)
